CREATE DATABASE IF NOT EXISTS hypnos_bdd;
  
CREATE TABLE IF NOT EXISTS User(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  Name NOT NULL VARCHAR(250),  
  Firstname NOT NULL VARCHAR(250),  
  Mail NOT NULL VARCHAR(250),  
  Password NOT NULL VARCHAR(250),  
  Role NOT NULL INTEGER,
  FOREIGN KEY(Role) REFERENCES User_Ref(ID),
  PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS Establishment(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  Address NOT NULL VARCHAR(250),
  City NOT NULL VARCHAR(250),
  Name NOT NULL VARCHAR(250),
  Manager NOT NULL INTEGER,
  FOREIGN KEY(Manager) REFERENCES User(ID),
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Suite(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  Title NOT NULL VARCHAR(250),  
  Establishment NOT NULL INTEGER,  
  Price NOT NULL DECIMAL,  
  IsOccupied NOT NULL BOOLEAN,  
  BookingLink NOT NULL VARCHAR(250),  
  Description NOT NULL VARCHAR(1000),  
  MainPic NOT NULL VARCHAR(250),  
  Gallery NOT NULL VARCHAR(250),
  FOREIGN KEY(Establishment) REFERENCES Establishment(ID),  
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Message(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  Name NOT NULL VARCHAR(250),
  Firstname NOT NULL VARCHAR(250),
  Mail NOT NULL VARCHAR(250),
  MessageBody NOT NULL VARCHAR(1000),
  Recipient NOT NULL INTEGER,
  Subject NOT NULL INTEGER,
  FOREIGN KEY(Recipient) REFERENCES User(ID), 
  FOREIGN KEY(Subject) REFERENCES SubjectMessage_Ref(ID), 
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS User_Ref(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  Label NOT NULL VARCHAR(250),
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Booking(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  StartingDate NOT NULL DATE,
  EndingDate NOT NULL DATE,
  Suite NOT NULL INTEGER,
  Client NOT NULL INTEGER,
  FOREIGN KEY(Suite) REFERENCES Suite(ID),
  FOREIGN KEY(Client) REFERENCES User(ID),
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS SubjectMessage_Ref(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  Label NOT NULL VARCHAR(250),
  PRIMARY KEY(ID)
);